[package]
name = "fin_config"
version = "0.1.1"
authors = ["toidiu <apoorv@toidiu.com>"]
description = "configs for fin."
keywords = ["iex", "api", "finance"]
categories = ["api-bindings"]
license = "MIT"
edition = '2018'

[dependencies]
serde = "~1.0"
serde_derive = "~1.0"
config = "~0.9"

