[app]
paseto_token = "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
cors_origin = "http://localhost:1234"

[database]
url = "postgres://postgres@localhost:5432/bio_task"

[iex]
token = "_____"
# debug is used so we can work on the logic without an internet connection
debug = true
